# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0013_urlconfrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='GistPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('gist_user', models.CharField(default=b'', help_text='Please supply the username of the GitHub user', max_length=32, verbose_name=b'GitHub User')),
                ('gist_id', models.CharField(default=b'', help_text='Please supply the ID of the gist', max_length=32, verbose_name=b'Gist ID')),
                ('filename', models.CharField(blank=True, default=b'', help_text='Optional. Supply a filename', max_length=64, verbose_name=b'GitHub File')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
